project:
  type: website

website:
  title: "    "
  site-url: "https://mroberts1.github.io/soundtracks"
  back-to-top-navigation: false
  search: false
  navbar:
    background: transparent
    foreground: "#1a1a1a"
    right:
      - text: home
        href: index.qmd
      - text: about
        href: about.qmd
      - icon: github
        href: https://github.com/mroberts1
      - icon: twitter
        href: https://twitter.com/mroberts_vma  

format:
  html:
    backgroundcolor: "#EFEDE5"
    theme:
      light: [litera, ember.scss]
      dark: [quartz, ember.scss]
    css: [custom.scss, custom-styles.css]
    linestretch: 1.8
    fontsize: 0.8em
    smooth-scroll: true
    linkcolor: "#1a1a1a"
    link-external-newwindow: true

execute:
  freeze: true
  cache: true
