project:
  type: website

website:
  title: "dorian ♭2"
  site-url: "https://mroberts1.github.io/soundtracks"
  back-to-top-navigation: false

format:
  html:
    backgroundcolor: "#EFEDE5"
    theme:
      light: [litera, ember.scss]
      dark: [quartz, ember.scss]
    css: [custom.scss, custom-styles.css]
    linestretch: 1.2
    fontsize: 0.9em
    smooth-scroll: true
    linkcolor: "#235440"
    link-external-newwindow: true

execute:
  freeze: true
  cache: true
